//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokenRequest
    {
        public int broken_request_id { get; set; }
        public int physical_people_id { get; set; }
        public int model_element_id { get; set; }
        public int broken_request_reason_id { get; set; }
        public System.DateTime date_to_repair { get; set; }
        public int isFinished { get; set; }
    
        public virtual PhysicalPeople PhysicalPeople { get; set; }
        public virtual ModelElement ModelElement { get; set; }
        public virtual sp_BrokenRequestReason sp_BrokenRequestReason { get; set; }
    }
}
