//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DragMetalOnEquipment
    {
        public int Drag_metal_on_equipment_id { get; set; }
        public Nullable<int> Equipment_object_id { get; set; }
        public Nullable<int> Drag_metal_id { get; set; }
        public Nullable<double> weight { get; set; }
        public string Other { get; set; }
    }
}
