//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElementsPlace
    {
        public int element_place_id { get; set; }
        public int model_element_id { get; set; }
        public int corpus_id { get; set; }
        public int floor { get; set; }
        public string room { get; set; }
        public System.DateTime date_begin { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public int move_reason_id { get; set; }
    
        public virtual ModelElement ModelElement { get; set; }
        public virtual sp_Corpus sp_Corpus { get; set; }
        public virtual sp_MoveReason sp_MoveReason { get; set; }
    }
}
