//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentsModel
    {
        public int Equipment_model_id { get; set; }
        public Nullable<int> Company_manufactorer_id { get; set; }
        public Nullable<int> Functional_purpose_id { get; set; }
        public string Full_name { get; set; }
        public string Apend_info { get; set; }
    }
}
