//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentObject
    {
        public int Equipment_object_id { get; set; }
        public Nullable<int> Equipment_model_id { get; set; }
        public string Inventory_number { get; set; }
        public Nullable<System.DateTime> Date_manufacture { get; set; }
        public string Port { get; set; }
        public Nullable<int> Country_id { get; set; }
        public string Serial_number { get; set; }
        public string Date_expluatation { get; set; }
        public Nullable<int> In_Buhgaltery { get; set; }
        public Nullable<System.DateTime> Date_debited { get; set; }
        public string Reason_for_debited { get; set; }
        public string OtherInfo { get; set; }
    }
}
