//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentPlace
    {
        public int Equipment_place_id { get; set; }
        public Nullable<int> Equipment_id { get; set; }
        public string Organisation_id { get; set; }
        public string Organisation_unit_id { get; set; }
        public Nullable<int> Corpus_id { get; set; }
        public string Floor { get; set; }
        public string Room { get; set; }
        public Nullable<System.DateTime> Date_localization_begin { get; set; }
        public Nullable<System.DateTime> Date_localization_finish { get; set; }
        public string Reason_to_move { get; set; }
    }
}
