//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaticalPhysicalPeoplePositions
    {
        public int fatical_physical_people_position_id { get; set; }
        public int physical_people_id { get; set; }
        public int organisation_id { get; set; }
        public int people_position_id { get; set; }
        public Nullable<System.DateTime> date_begin { get; set; }
        public Nullable<System.DateTime> date_end { get; set; }
        public int salary { get; set; }
    
        public virtual PhysicalPeople PhysicalPeople { get; set; }
        public virtual Organisations Organisations { get; set; }
        public virtual sp_PysicalPeoplePositions sp_PysicalPeoplePositions { get; set; }
    }
}
