//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelToPurchase
    {
        public int model_purchase_id { get; set; }
        public int purchase_id { get; set; }
        public int model_element_id { get; set; }
    
        public virtual ModelElement ModelElement { get; set; }
        public virtual Purchase Purchase { get; set; }
    }
}
