//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabaseEntities : DbContext
    {
        public DatabaseEntities()
            : base("name=DatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Corpus> Corpus { get; set; }
        public virtual DbSet<DragMetalOnEquipment> DragMetalOnEquipment { get; set; }
        public virtual DbSet<EquipmentModel> EquipmentModel { get; set; }
        public virtual DbSet<EquipmentObject> EquipmentObject { get; set; }
        public virtual DbSet<EquipmentPlace> EquipmentPlace { get; set; }
        public virtual DbSet<EquipmentsModel> EquipmentsModel { get; set; }
        public virtual DbSet<MOUser> MOUser { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<PeoplePosition> PeoplePosition { get; set; }
        public virtual DbSet<PersonalRole> PersonalRole { get; set; }
        public virtual DbSet<PhysicalPeople> PhysicalPeople { get; set; }
        public virtual DbSet<S_BrokenItem> S_BrokenItem { get; set; }
        public virtual DbSet<S_BrokenReason> S_BrokenReason { get; set; }
        public virtual DbSet<S_CansellerationReason> S_CansellerationReason { get; set; }
        public virtual DbSet<S_Corpus> S_Corpus { get; set; }
        public virtual DbSet<S_Country> S_Country { get; set; }
        public virtual DbSet<S_DisplacementCause> S_DisplacementCause { get; set; }
        public virtual DbSet<S_DragMetal> S_DragMetal { get; set; }
        public virtual DbSet<S_ExpluatationRole> S_ExpluatationRole { get; set; }
        public virtual DbSet<S_FunctionalPurpose> S_FunctionalPurpose { get; set; }
        public virtual DbSet<S_OrganisationType> S_OrganisationType { get; set; }
        public virtual DbSet<S_OrganisationUnit> S_OrganisationUnit { get; set; }
        public virtual DbSet<S_PersonalRole> S_PersonalRole { get; set; }
        public virtual DbSet<S_PmElement> S_PmElement { get; set; }
        public virtual DbSet<S_Position> S_Position { get; set; }
        public virtual DbSet<S_PurchaseType> S_PurchaseType { get; set; }
        public virtual DbSet<S_Service> S_Service { get; set; }
        public virtual DbSet<S_ServiceOperation> S_ServiceOperation { get; set; }
        public virtual DbSet<S_ZipElement> S_ZipElement { get; set; }
        public virtual DbSet<ServiceMaintenance> ServiceMaintenance { get; set; }
        public virtual DbSet<ServiceMaintenanceOperation> ServiceMaintenanceOperation { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
