//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MainDatabaseEntities5 : DbContext
    {
        public MainDatabaseEntities5()
            : base("name=MainDatabaseEntities5")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BrokenRequest> BrokenRequests { get; set; }
        public virtual DbSet<ElementsDragMetal> ElementsDragMetals { get; set; }
        public virtual DbSet<ElementsPlace> ElementsPlaces { get; set; }
        public virtual DbSet<FaticalPhysicalPeoplePosition> FaticalPhysicalPeoplePositions { get; set; }
        public virtual DbSet<ModelElement> ModelElements { get; set; }
        public virtual DbSet<ModelToPurchase> ModelToPurchases { get; set; }
        public virtual DbSet<ModelType> ModelTypes { get; set; }
        public virtual DbSet<MOExpluatation> MOExpluatations { get; set; }
        public virtual DbSet<Organisation> Organisations { get; set; }
        public virtual DbSet<PersonalOnService> PersonalOnServices { get; set; }
        public virtual DbSet<PhysicalPeople> PhysicalPeoples { get; set; }
        public virtual DbSet<Purchase> Purchases { get; set; }
        public virtual DbSet<PurchaseElement> PurchaseElements { get; set; }
        public virtual DbSet<sp_BrokenRequestReason> sp_BrokenRequestReason { get; set; }
        public virtual DbSet<sp_Corpus> sp_Corpus { get; set; }
        public virtual DbSet<sp_CountryKey> sp_CountryKey { get; set; }
        public virtual DbSet<sp_DragMetal> sp_DragMetal { get; set; }
        public virtual DbSet<sp_ExpluatationRole> sp_ExpluatationRole { get; set; }
        public virtual DbSet<sp_FunctionalyUseModel> sp_FunctionalyUseModel { get; set; }
        public virtual DbSet<sp_MoveReason> sp_MoveReason { get; set; }
        public virtual DbSet<sp_OrganisationDepartment> sp_OrganisationDepartment { get; set; }
        public virtual DbSet<sp_OrganisationType> sp_OrganisationType { get; set; }
        public virtual DbSet<sp_PurchaseType> sp_PurchaseType { get; set; }
        public virtual DbSet<sp_PysicalPeoplePositions> sp_PysicalPeoplePositions { get; set; }
        public virtual DbSet<sp_ReasonWriteOff> sp_ReasonWriteOff { get; set; }
        public virtual DbSet<sp_ServiceOperationPersonalRole> sp_ServiceOperationPersonalRole { get; set; }
        public virtual DbSet<sp_ServiceOperationType> sp_ServiceOperationType { get; set; }
        public virtual DbSet<sp_ServiceType> sp_ServiceType { get; set; }
        public virtual DbSet<sp_Standarts> sp_Standarts { get; set; }
        public virtual DbSet<sp_ZIP_AND_PM_Element> sp_ZIP_AND_PM_Element { get; set; }
        public virtual DbSet<ZIPPMDocumentsOnPurchase> ZIPPMDocumentsOnPurchases { get; set; }
        public virtual DbSet<ZIPPMMove> ZIPPMMoves { get; set; }
        public virtual DbSet<ZIPPMonStock> ZIPPMonStocks { get; set; }
    }
}
