//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelElement()
        {
            this.BrokenRequest = new HashSet<BrokenRequest>();
            this.ElementsDragMetal = new HashSet<ElementsDragMetal>();
            this.ElementsPlaces = new HashSet<ElementsPlaces>();
            this.ModelToPurchase = new HashSet<ModelToPurchase>();
            this.MOExpluatation = new HashSet<MOExpluatation>();
            this.PersonalOnService = new HashSet<PersonalOnService>();
            this.PurchaseElements = new HashSet<PurchaseElements>();
            this.ZIPPMMoves = new HashSet<ZIPPMMoves>();
        }
    
        public int model_element_id { get; set; }
        public string inventory_number { get; set; }
        public int model_type_id { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public string serial_number { get; set; }
        public Nullable<System.DateTime> date_utilisation { get; set; }
        public string other { get; set; }
        public int reason_write_off_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrokenRequest> BrokenRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementsDragMetal> ElementsDragMetal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementsPlaces> ElementsPlaces { get; set; }
        public virtual ModelType ModelType { get; set; }
        public virtual sp_ReasonWriteOff sp_ReasonWriteOff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelToPurchase> ModelToPurchase { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOExpluatation> MOExpluatation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalOnService> PersonalOnService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseElements> PurchaseElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZIPPMMoves> ZIPPMMoves { get; set; }
    }
}
