//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelType()
        {
            this.ModelElement = new HashSet<ModelElement>();
        }
    
        public int model_type_id { get; set; }
        public string model_type_name { get; set; }
        public int organisation_id { get; set; }
        public int functionaly_use_model_id { get; set; }
        public int expluatation_role_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelElement> ModelElement { get; set; }
        public virtual Organisations Organisations { get; set; }
        public virtual sp_FunctionalyUseModel sp_FunctionalyUseModel { get; set; }
        public virtual sp_ExpluatationRole sp_ExpluatationRole { get; set; }
    }
}
