//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModelElement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModelElement()
        {
            this.BrokenRequests = new HashSet<BrokenRequest>();
            this.ElementsDragMetals = new HashSet<ElementsDragMetal>();
            this.ElementsPlaces = new HashSet<ElementsPlace>();
            this.ModelToPurchases = new HashSet<ModelToPurchase>();
            this.MOExpluatations = new HashSet<MOExpluatation>();
            this.PersonalOnServices = new HashSet<PersonalOnService>();
            this.PurchaseElements = new HashSet<PurchaseElement>();
            this.ZIPPMMoves = new HashSet<ZIPPMMove>();
        }
    
        public int model_element_id { get; set; }
        public string inventory_number { get; set; }
        public int model_type_id { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public string serial_number { get; set; }
        public Nullable<System.DateTime> date_utilisation { get; set; }
        public string other { get; set; }
        public int reason_write_off_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrokenRequest> BrokenRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementsDragMetal> ElementsDragMetals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ElementsPlace> ElementsPlaces { get; set; }
        public virtual ModelType ModelType { get; set; }
        public virtual sp_ReasonWriteOff sp_ReasonWriteOff { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelToPurchase> ModelToPurchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOExpluatation> MOExpluatations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalOnService> PersonalOnServices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseElement> PurchaseElements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZIPPMMove> ZIPPMMoves { get; set; }
    }
}
