//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOUser
    {
        public int MO_user_id { get; set; }
        public Nullable<int> Position_id { get; set; }
        public Nullable<int> Position_type_id { get; set; }
        public Nullable<int> Physical_people_id { get; set; }
        public Nullable<int> equipment_id { get; set; }
        public Nullable<System.DateTime> Date_begin { get; set; }
        public Nullable<System.DateTime> Date_finish { get; set; }
        public Nullable<int> Model_role_id { get; set; }
    }
}
