//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeoplePosition
    {
        public int People_position_id { get; set; }
        public Nullable<int> Physical_people_id { get; set; }
        public Nullable<int> Organisation_id { get; set; }
        public Nullable<int> Position_id { get; set; }
        public Nullable<int> Position_type_id { get; set; }
        public Nullable<System.DateTime> DateBegin { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public Nullable<int> Salary { get; set; }
        public string Other_info { get; set; }
    }
}
