//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalPeople
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhysicalPeople()
        {
            this.BrokenRequests = new HashSet<BrokenRequest>();
            this.FaticalPhysicalPeoplePositions = new HashSet<FaticalPhysicalPeoplePosition>();
            this.MOExpluatations = new HashSet<MOExpluatation>();
            this.PersonalOnServices = new HashSet<PersonalOnService>();
        }
    
        public int physical_people_id { get; set; }
        public string family { get; set; }
        public string name { get; set; }
        public string patronumic { get; set; }
        public Nullable<int> Gender { get; set; }
        public string contacts { get; set; }
        public string other { get; set; }
        public int organisation_department_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BrokenRequest> BrokenRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaticalPhysicalPeoplePosition> FaticalPhysicalPeoplePositions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MOExpluatation> MOExpluatations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonalOnService> PersonalOnServices { get; set; }
        public virtual sp_OrganisationDepartment sp_OrganisationDepartment { get; set; }
    }
}
