//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int purchase_id { get; set; }
        public int purchase_type_id { get; set; }
        public string purchase_document_number { get; set; }
        public Nullable<System.DateTime> date_apply { get; set; }
        public Nullable<int> organisation_id { get; set; }
    
        public virtual Organisations Organisations { get; set; }
        public virtual sp_PurchaseType sp_PurchaseType { get; set; }
    }
}
