//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_OrganisationUnit
    {
        public int Organisation_unit_id { get; set; }
        public Nullable<int> Organisation_id { get; set; }
        public string Organisation_name { get; set; }
        public Nullable<int> Corpus_id { get; set; }
        public string Group_category { get; set; }
        public string Other { get; set; }
    }
}
