//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Position
    {
        public int Position_id { get; set; }
        public Nullable<int> Position_type_id { get; set; }
        public string Position_name { get; set; }
        public Nullable<int> Bad_position { get; set; }
    }
}
