//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceMaintenanceOperation
    {
        public int Service_maintenance_operation_id { get; set; }
        public Nullable<int> Functional_purpose_id { get; set; }
        public Nullable<int> Equipment_object_id { get; set; }
        public Nullable<int> Service_maintenance_id { get; set; }
        public Nullable<int> Service_operation_id { get; set; }
    }
}
