//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceMaintenance
    {
        public int Service_maintenance_id { get; set; }
        public Nullable<int> Functional_purpose_id { get; set; }
        public Nullable<int> Equipment_model_id { get; set; }
        public Nullable<int> Service_id { get; set; }
        public Nullable<System.DateTime> Time_begin { get; set; }
        public Nullable<System.DateTime> Time_finish { get; set; }
        public string Service_Result { get; set; }
        public string Other { get; set; }
    }
}
