//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_PysicalPeoplePositions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sp_PysicalPeoplePositions()
        {
            this.FaticalPhysicalPeoplePositions = new HashSet<FaticalPhysicalPeoplePosition>();
        }
    
        public int physical_people_position_id { get; set; }
        public string physical_people_position_name { get; set; }
        public string other { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaticalPhysicalPeoplePosition> FaticalPhysicalPeoplePositions { get; set; }
    }
}
