//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_Standarts
    {
        public int standart_id { get; set; }
        public int corpus_id { get; set; }
        public int count { get; set; }
        public int model_type_id { get; set; }
    
        public virtual ModelType ModelType { get; set; }
        public virtual sp_Corpus sp_Corpus { get; set; }
    }
}
