//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp_ZIP_AND_PM_Element
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public sp_ZIP_AND_PM_Element()
        {
            this.ZIPPMDocumentsOnPurchases = new HashSet<ZIPPMDocumentsOnPurchase>();
            this.ZIPPMMoves = new HashSet<ZIPPMMove>();
            this.ZIPPMonStocks = new HashSet<ZIPPMonStock>();
        }
    
        public int zipPM_element_id { get; set; }
        public string zipPM_element_name { get; set; }
        public int isZIP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZIPPMDocumentsOnPurchase> ZIPPMDocumentsOnPurchases { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZIPPMMove> ZIPPMMoves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZIPPMonStock> ZIPPMonStocks { get; set; }
    }
}
