//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZIPPMonStock
    {
        public int zipPM_on_stock_id { get; set; }
        public int zipPM_element_id { get; set; }
        public int count { get; set; }
        public string other { get; set; }
    
        public virtual sp_ZIP_AND_PM_Element sp_ZIP_AND_PM_Element { get; set; }
    }
}
