//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZIPPMMove
    {
        public int zipPM_move_id { get; set; }
        public System.DateTime date_move { get; set; }
        public int model_element_id { get; set; }
        public int zipPM_element_id { get; set; }
    
        public virtual ModelElement ModelElement { get; set; }
        public virtual sp_ZIP_AND_PM_Element sp_ZIP_AND_PM_Element { get; set; }
    }
}
