//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalComponents.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZIPPMDocumentsOnPurchase
    {
        public int zipPM_documents_purchase_id { get; set; }
        public int zipPM_element_id { get; set; }
        public int count { get; set; }
        public System.DateTime date_coming_in { get; set; }
        public Nullable<System.DateTime> date_to_end_possible_use { get; set; }
    
        public virtual sp_ZIP_AND_PM_Element sp_ZIP_AND_PM_Element { get; set; }
    }
}
